<?php
require_once __DIR__ . '/config/init_sekolah.php';
require_once __DIR__ . '/core/Database.php';
require_once __DIR__ . '/core/App.php';
require_once __DIR__ . '/core/functions.php';

App::requireLogin();
App::requireRole(['admin']);

$host = defined('DB_HOST') ? DB_HOST : 'localhost';
$user = defined('DB_USER') ? DB_USER : 'root';
$pass = defined('DB_PASS') ? DB_PASS : '';
$dbname = defined('DB_NAME') ? DB_NAME : 'inventaris_labkom';
$port = defined('DB_PORT') ? DB_PORT : '3306';

if ($host === 'localhost') {
    $host = '127.0.0.1';
}

$filename = 'inventaris-labkom-' . date('Y-m-d') . '.sql';

header('Content-Type: application/sql');
header('Content-Disposition: attachment; filename="' . $filename . '"');

$dumped = false;

if (function_exists('exec')) {
    $cmd = sprintf(
        'mysqldump --host=%s --port=%s --user=%s --password=%s %s 2>/dev/null',
        escapeshellarg($host),
        escapeshellarg($port),
        escapeshellarg($user),
        escapeshellarg($pass),
        escapeshellarg($dbname)
    );
    exec($cmd, $output, $exitCode);
    if ($exitCode === 0 && !empty($output)) {
        echo implode("\n", $output);
        $dumped = true;
    }
}

if (!$dumped) {
    $conn = Database::getInstance()->getConnection();

    echo "-- Backup generated by PHP (" . date('Y-m-d H:i:s') . ")\n";
    echo "-- Database: " . $dbname . "\n";
    echo "-- --------------------------------------------------\n\n";

    echo "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    echo "SET AUTOCOMMIT = 0;\n";
    echo "START TRANSACTION;\n";
    echo "SET time_zone = '+00:00';\n\n";

    $tablesResult = $conn->query("SHOW TABLES");
    while ($tableRow = $tablesResult->fetch_array()) {
        $table = $tableRow[0];

        echo "-- --------------------------------------------------\n";
        echo "-- Table structure for `$table`\n";
        echo "-- --------------------------------------------------\n\n";

        $createResult = $conn->query("SHOW CREATE TABLE `$table`");
        $createRow = $createResult->fetch_array();
        echo $createRow[1] . ";\n\n";

        echo "-- Dumping data for `$table`\n";
        echo "--\n\n";

        $dataResult = $conn->query("SELECT * FROM `$table`");
        $columns = [];
        while ($colInfo = $dataResult->fetch_field()) {
            $columns[] = $colInfo->name;
        }
        $colList = '`' . implode('`, `', $columns) . '`';

        if ($dataResult->num_rows > 0) {
            echo "INSERT INTO `$table` ($colList) VALUES\n";
            $rowNum = 0;
            while ($dataRow = $dataResult->fetch_assoc()) {
                $values = [];
                foreach ($columns as $col) {
                    $val = $dataRow[$col];
                    if ($val === null) {
                        $values[] = 'NULL';
                    } else {
                        $values[] = "'" . $conn->real_escape_string($val) . "'";
                    }
                }
                $rowNum++;
                $comma = ($rowNum < $dataResult->num_rows) ? ',' : ';';
                echo "(" . implode(', ', $values) . ")" . $comma . "\n";
            }
            echo "\n";
        }

        echo "\n";
    }

    echo "COMMIT;\n";
}

exit;
